# @package _global_

predictor:
  random_seed: ${constants.seed}
  optim_kwargs:
    lr: 1.e-4
  torch_scheduler_kwargs:
    module_type: WarmUpLinearLR
    max_num_epochs: &max_epochs 100
    warmup_epochs: 5
    verbose: False
  scheduler_kwargs:
  target_nan_mask: null
  multitask_handling: flatten

trainer:
  seed: ${constants.seed}
  logger:
    save_dir: logs/dti_v2/
    name: ${constants.name}
    project: ${constants.name}
  model_checkpoint:
    dirpath: model_checkpoints/dti_v2/${now:%Y-%m-%d_%H-%M-%S}/
    filename: ${constants.name}
    save_last: True
  trainer:
    precision: 16-mixed
    max_epochs: ${predictor.torch_scheduler_kwargs.max_num_epochs}
    min_epochs: 1
    check_val_every_n_epoch: 5
