# @package _global_

predictor:
  metrics_on_progress_bar:
    l1000_vcap: []
    l1000_mcf7: []
    pcba_1328: []
    pcqm4m_g25: []
    pcqm4m_n4: []
    rxrx3: ['mae']
  metrics_on_training_set:
    l1000_vcap: []
    l1000_mcf7: []
    pcba_1328: []
    pcqm4m_g25: []
    pcqm4m_n4: []
    rxrx3: []
  loss_fun:
    rxrx3: mae_ipu
    l1000_vcap:
      name: hybrid_ce_ipu
      n_brackets: 3
      alpha: 0.5
    l1000_mcf7:
      name: hybrid_ce_ipu
      n_brackets: 3
      alpha: ${predictor.loss_fun.l1000_vcap.alpha}
    pcba_1328: bce_logits_ipu
    pcqm4m_g25: mae_ipu
    pcqm4m_n4: mae_ipu


metrics:
  rxrx3:
  - name: mae
    metric: mae_ipu
  - name: pearsonr
    metric: pearsonr_ipu
  l1000_vcap: &classif_metrics
    - name: auroc
      metric: auroc
      num_classes: 3
      task: multiclass
      target_to_int: True
      target_nan_mask: -1000
      ignore_index: -1000
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: avpr
      metric: averageprecision
      num_classes: 3
      task: multiclass
      target_to_int: True
      target_nan_mask: -1000
      ignore_index: -1000
      multitask_handling: mean-per-label
      threshold_kwargs: null
  l1000_mcf7: *classif_metrics
  pcba_1328:
    - name: auroc
      metric: auroc
      task: binary
      multitask_handling: mean-per-label
      target_nan_mask: ignore
      threshold_kwargs: null
    - name: avpr
      metric: averageprecision
      task: binary
      multitask_handling: mean-per-label
      target_nan_mask: ignore
      threshold_kwargs: null
  pcqm4m_g25: &pcqm_metrics
    - name: mae
      metric: mae_ipu
      target_nan_mask: null
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: pearsonr
      metric: pearsonr_ipu
      threshold_kwargs: null
      target_nan_mask: null
      multitask_handling: mean-per-label
    - name: r2
      metric: r2_score_ipu
      threshold_kwargs: null
      target_nan_mask: null
      multitask_handling: mean-per-label
  pcqm4m_n4: *pcqm_metrics


datamodule:
  args:
    task_specific_args:
      rxrx3:
        df_path: /home/shpark/prj-molrepr/graphium/data/rxrx3/rxrx3_smiles_embeddings.csv
        smiles_col: "SMILES_nometa"
        label_cols: feature_*
        split_val: 0.1
        split_test: 0.1
        seed: 0
        task_level: graph
        # label_normalization:
        #   normalize_val_test: True
        #   method: "normal"
      l1000_vcap:
        df: null
        df_path: ./data/graphium/neurips2023/large-dataset/LINCS_L1000_VCAP_0-2_th2.csv.gz
        smiles_col: "SMILES"
        label_cols: geneID-*  # geneID-* means all columns starting with "geneID-"
        task_level: graph
        splits_path: ./data/graphium/neurips2023/large-dataset/l1000_vcap_random_splits.pt  # Download with `wget https://storage.valencelabs.com/graphium/datasets/neurips_2023/Large-dataset/l1000_vcap_random_splits.pt`
        epoch_sampling_fraction: 1.0
      l1000_mcf7:
        df: null
        df_path: ./data/graphium/neurips2023/large-dataset/LINCS_L1000_MCF7_0-2_th2.csv.gz
        smiles_col: "SMILES"
        label_cols: geneID-*  # geneID-* means all columns starting with "geneID-"
        task_level: graph
        splits_path: ./data/graphium/neurips2023/large-dataset/l1000_mcf7_random_splits.pt  # Download with `wget https://storage.valencelabs.com/graphium/datasets/neurips_2023/Large-dataset/l1000_mcf7_random_splits.pt`
        epoch_sampling_fraction: 1.0
      pcba_1328:
        df: null
        df_path: ./data/graphium/neurips2023/large-dataset/PCBA_1328_1564k.parquet
        smiles_col: "SMILES"
        label_cols: assayID-*  # assayID-* means all columns starting with "assayID-"
        task_level: graph
        splits_path: ./data/graphium/neurips2023/large-dataset/pcba_1328_random_splits.pt  # Download with `wget https://storage.valencelabs.com/graphium/datasets/neurips_2023/Large-dataset/pcba_1328_random_splits.pt`
        epoch_sampling_fraction: 1.0
      pcqm4m_g25:
        df: null
        df_path: ./data/graphium/neurips2023/large-dataset/PCQM4M_G25_N4.parquet
        smiles_col: "ordered_smiles"
        label_cols: graph_*  # graph_* means all columns starting with "graph_"
        task_level: graph
        splits_path: ./data/graphium/neurips2023/large-dataset/pcqm4m_g25_n4_random_splits.pt  # Download with `wget https://storage.valencelabs.com/graphium/datasets/neurips_2023/Large-dataset/pcqm4m_g25_n4_random_splits.pt`
        label_normalization:
          normalize_val_test: True
          method: "normal"
        epoch_sampling_fraction: 1.0
      pcqm4m_n4:
        df: null
        df_path: ./data/graphium/neurips2023/large-dataset/PCQM4M_G25_N4.parquet
        smiles_col: "ordered_smiles"
        label_cols: node_* # node_* means all columns starting with "node_"
        task_level: node
        splits_path: ./data/graphium/neurips2023/large-dataset/pcqm4m_g25_n4_random_splits.pt  # Download with `wget https://storage.valencelabs.com/graphium/datasets/neurips_2023/Large-dataset/pcqm4m_g25_n4_random_splits.pt`
        seed: 42
        label_normalization:
          normalize_val_test: True
          method: "normal"
        epoch_sampling_fraction: 1.0
    num_workers: 64

architecture:
  task_heads:
    rxrx3:
      task_level: graph
      out_dim: 384
      hidden_dims: 128
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    l1000_vcap:
      task_level: graph
      out_dim: 2934
      hidden_dims: 256
      depth: 2
      activation: none
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    l1000_mcf7:
      task_level: graph
      out_dim: 2934
      hidden_dims: 256
      depth: 2
      activation: none
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    pcba_1328:
      task_level: graph
      out_dim: 1328
      hidden_dims: 128
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    pcqm4m_g25:
      task_level: graph
      out_dim: 25
      hidden_dims: 64
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    pcqm4m_n4:
      task_level: node
      out_dim: 4
      hidden_dims: 64
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none